### ISSUE TITLE
Inverse weights are not computed correctly

### ISSUE THREAD

**Issue by ngreifer** [FarhadPishgar/MatchIt.mice#1]
https://github.com/FarhadPishgar/MatchIt.mice/blob/e4de735d9de6ffaea96838f60cc847817fc5412f/R/weightitmice.R#L117-L119

This doesn't do what you might think it does. The correct code should be:

```{r}
dataset["inverse.weights"] <- ifelse(dataset[,paste(terms(formula)[[2]])] == 1,
                                     1 / (dataset$distance),
                                     1 / (1 - dataset$distance))
```

**Comment by FarhadPishgar** [comment]
Thanks for alerting, Noah.
I will rectify this issue in an update, very soon.
